# Tensors Basics #

In [2]:
import torch
import numpy as np 

### 1.) Creating a Tensor 

In [3]:
data1=[1,2,3,4,5,6,7]
data2=np.array([1.5,2.5,3.5,4.5,5.5,6.5,7.5])

In [5]:
t1=torch.tensor(data1)
print(t1)

tensor([1, 2, 3, 4, 5, 6, 7])


In [6]:
t1=torch.Tensor(data1)
print(t1)

tensor([1., 2., 3., 4., 5., 6., 7.])


In [7]:
t1=torch.as_tensor(data1)
print(t1)

tensor([1, 2, 3, 4, 5, 6, 7])


In [8]:
t2=torch.from_numpy(data2)
print(t2)

tensor([1.5000, 2.5000, 3.5000, 4.5000, 5.5000, 6.5000, 7.5000],
       dtype=torch.float64)


### 2.) Creating a random tensor and finding details #

In [12]:
some_tensor= torch.rand(3,3)
print(some_tensor)

tensor([[0.0072, 0.5734, 0.4472],
        [0.2685, 0.5442, 0.8123],
        [0.1473, 0.3943, 0.7812]])


In [16]:
some_tensor.shape


torch.Size([3, 3])

In [17]:
some_tensor.dtype

torch.float32

In [18]:
some_tensor.device

device(type='cpu')

### 3.) Restructuring Tensors ###

In [5]:
t1=torch.rand(3,4)
print(t1)

tensor([[0.5382, 0.4915, 0.9389, 0.1469],
        [0.7313, 0.1327, 0.4245, 0.1572],
        [0.3085, 0.3850, 0.6520, 0.4683]])


In [7]:
t1.reshape(4,3)

tensor([[0.5382, 0.4915, 0.9389],
        [0.1469, 0.7313, 0.1327],
        [0.4245, 0.1572, 0.3085],
        [0.3850, 0.6520, 0.4683]])

In [8]:
t1.resize(4,3)

/Users/arnavkarnik/Documents/MIT-Manipal_CSE-AI-ML/.venv/lib/python3.9/site-packages/torch/_tensor.py:955: UserWarning: non-inplace resize is deprecated
  warnings.warn("non-inplace resize is deprecated")


tensor([[0.5382, 0.4915, 0.9389],
        [0.1469, 0.7313, 0.1327],
        [0.4245, 0.1572, 0.3085],
        [0.3850, 0.6520, 0.4683]])

##### Indexing a Tensor #####

In [20]:
t1[1,2]

tensor(0.4245)

### 4.) Matrix Multiplication in Tensors ###

##### a) Matrix Multiplication using Transpose 

In [21]:
t1=torch.rand(3,2)
t2=torch.rand(3,2)
t3=torch.matmul(t1,t2.T)
print(t3)

tensor([[1.0549, 1.0438, 0.7478],
        [0.7722, 0.6045, 0.6599],
        [0.9948, 0.8671, 0.7879]])


##### b) Using torch.mm()

In [22]:
t1=torch.rand(4,5)
t2=torch.rand(5,6)
t3=torch.mm(t1,t2,out=None)
print(t3)


tensor([[0.8829, 0.4164, 1.1491, 1.0855, 1.0619, 0.5379],
        [0.7439, 1.0089, 1.5562, 1.1600, 1.7166, 0.8323],
        [0.9573, 0.8896, 1.2955, 1.2196, 1.3903, 0.8132],
        [1.4168, 0.9766, 2.0265, 1.7177, 1.9613, 1.0038]])


##### c) Using torch.matmul()

In [29]:
t1=torch.rand(7,8)
t2=torch.rand(8,9)
t3=torch.matmul(t1,t2,out=None)
print(t3)

tensor([[1.8747, 1.7904, 1.8425, 1.1411, 2.3361, 1.9493, 2.3277, 2.4531, 2.1082],
        [1.7552, 1.7735, 2.1848, 2.2461, 3.1910, 2.0649, 1.7584, 2.6394, 2.2147],
        [1.9727, 1.7262, 2.3651, 2.5013, 3.3675, 2.5335, 2.1102, 2.8234, 2.7549],
        [1.6720, 1.7895, 1.6926, 1.4487, 2.3873, 2.0101, 2.1152, 2.1658, 1.8751],
        [1.1594, 1.5365, 1.2476, 0.9574, 1.7169, 1.5696, 1.6820, 1.6158, 1.5419],
        [1.9408, 1.2140, 1.9759, 2.1907, 2.7517, 2.1331, 1.6945, 2.6492, 2.1572],
        [2.3042, 2.1284, 2.1287, 2.5186, 3.4738, 2.7831, 1.9783, 2.9613, 2.5603]])


##### d) Using torch.bmm()

In [31]:
t1=torch.rand(3,3,3)
t2=torch.rand(3,3,3)
t3=torch.bmm(t1,t2,out=None)
print(t3)

tensor([[[1.1131, 0.5593, 0.9149],
         [0.6328, 0.1585, 0.6101],
         [0.5456, 0.2602, 0.5377]],

        [[0.8530, 0.8889, 0.7851],
         [0.3471, 0.6850, 0.7182],
         [0.4068, 0.8159, 0.9539]],

        [[1.2085, 0.8464, 1.4425],
         [0.6024, 0.3080, 0.9608],
         [0.6064, 0.4234, 0.7324]]])


##### e) Using @ operator 

In [32]:
t1=torch.rand(4,4,4,4)
t2=torch.rand(4,4,4,4)
t3=t1@t2
print(t3)

tensor([[[[0.9720, 0.8484, 0.6735, 0.7445],
          [1.3046, 0.8786, 0.4609, 0.7810],
          [1.2870, 1.0358, 0.7012, 1.0770],
          [1.0964, 0.8266, 0.4384, 0.7704]],

         [[1.4333, 1.7672, 1.1383, 1.7362],
          [0.9481, 0.7073, 0.3460, 1.0509],
          [1.8619, 2.3827, 1.5812, 2.1996],
          [1.2555, 1.8145, 1.2017, 1.5609]],

         [[0.8438, 0.8597, 0.4367, 1.4943],
          [1.2024, 0.9383, 0.5457, 1.9320],
          [0.7880, 0.6110, 0.3418, 1.5631],
          [1.0937, 0.8626, 0.5276, 1.5262]],

         [[1.1446, 1.6451, 1.5844, 0.7820],
          [0.9360, 1.5237, 1.4522, 0.5653],
          [1.1868, 1.2081, 1.2447, 0.9833],
          [0.2634, 0.2716, 0.1760, 0.1530]]],


        [[[2.0876, 2.4066, 1.1055, 1.0906],
          [1.0422, 1.4038, 1.0333, 0.8256],
          [1.8429, 2.4410, 1.1663, 1.1947],
          [1.0049, 1.1494, 0.6038, 0.6349]],

         [[0.9801, 0.8900, 1.0483, 1.4065],
          [0.3798, 0.3695, 0.3986, 0.3919],
          [0.3449, 0