# Tensors Basics #

In [2]:
import torch
import numpy as np 

### 1.) Creating a Tensor 

In [3]:
data1=[1,2,3,4,5,6,7]
data2=np.array([1.5,2.5,3.5,4.5,5.5,6.5,7.5])

In [5]:
t1=torch.tensor(data1)
print(t1)

tensor([1, 2, 3, 4, 5, 6, 7])


In [6]:
t1=torch.Tensor(data1)
print(t1)

tensor([1., 2., 3., 4., 5., 6., 7.])


In [7]:
t1=torch.as_tensor(data1)
print(t1)

tensor([1, 2, 3, 4, 5, 6, 7])


In [8]:
t2=torch.from_numpy(data2)
print(t2)

tensor([1.5000, 2.5000, 3.5000, 4.5000, 5.5000, 6.5000, 7.5000],
       dtype=torch.float64)


### 2.) Creating a random tensor and finding details #

In [12]:
some_tensor= torch.rand(3,3)
print(some_tensor)

tensor([[0.0072, 0.5734, 0.4472],
        [0.2685, 0.5442, 0.8123],
        [0.1473, 0.3943, 0.7812]])


In [16]:
some_tensor.shape


torch.Size([3, 3])

In [17]:
some_tensor.dtype

torch.float32

In [18]:
some_tensor.device

device(type='cpu')